name: DeathPenalty
main: com.verybigcorp.deathpenalty.DeathPenalty
version: 2.2
commands:
   dp: 
      description: DeathPenalty
      permission: 
      usage: /dp help
   timeleft: 
      description: Get the time left if you're a ghost
      permission: 
      usage: /timeleft